spring.application.name=ads-graphql-webapi

server.port=8085

spring.graphql.graphiql.enabled=true

spring.datasource.url=${ADS_DB_URL:jdbc:postgresql://localhost:5432/ads_db}
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

