spring.application.name=ads-lab7b-graphql-welcome

server.port=8080

# GraphQL
spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=false

# Postgres (local docker)
# Note: container name (postgres1) doesn't matter unless you're connecting from another container.
spring.datasource.url=jdbc:postgresql://localhost:5432/ads_lab7b_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

