apiVersion: v1
kind: Namespace
metadata:
  name: ads

---
apiVersion: v1
kind: Secret
metadata:
  name: ads-secrets
  namespace: ads
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  ADS_SECURITY_JWT_SECRET: change-me-to-a-long-random-secret-change-me-to-a-long-random-secret

